import type { Character, CharacterState } from "../types/character";
import type { LangCode } from "../store/boxStore";
import { getDisplayName } from "../utils/i18n";
import { getUiText } from "../i18n/ui";
import { PortrayBadge } from "./PortrayBadge";

interface ExportCanvasProps {
  characters: Character[];
  states: Record<string, CharacterState>;
  lang: LangCode;
}

/** 離屏匯出層：畫布寬度依欄數精算，不含任何操作介面（spec §24.2、§24.4） */
export function ExportCanvas({ characters, states, lang }: ExportCanvasProps) {
  const t = getUiText(lang);
  const owned = characters.filter((c) => states[c.id]?.owned);
  const fullPortray = owned.filter((c) => states[c.id]?.portray === 5).length;
  const columns = owned.length > 50 ? 10 : Math.min(owned.length, 5) || 1;
  // 卡片 112px + 邊框 2px = 114px，間距 10px
  const gridWidth = columns * 114 + (columns - 1) * 10;

  return (
    <div className="export-canvas" style={{ width: gridWidth + 100 }}>
      <div className="export-canvas__header">
        <div>
          <span className="export-canvas__eyebrow">{t.eyebrow}</span>
          <h2 className="export-canvas__title">{t.appTitle}</h2>
        </div>
        <div className="export-canvas__stats">
          <span>
            {t.owned} {owned.length} / {characters.length}
          </span>
          <span>
            {t.fullPortray} {fullPortray}
          </span>
        </div>
      </div>

      <div className="export-grid" style={{ gridTemplateColumns: `repeat(${columns}, auto)` }}>
        {owned.map((character) => (
          <div key={character.id} className="export-card">
            <div className="export-card__image-frame">
              <img
                className="export-card__image"
                src={import.meta.env.BASE_URL + character.images.avatar.replace(/^\//, "")}
                alt={getDisplayName(character, lang)}
              />
              <PortrayBadge
                level={states[character.id]?.portray ?? 0}
                lang={lang}
                position="bottom"
              />
            </div>
            <div className="export-card__name">
              {getDisplayName(character, lang)}
            </div>
          </div>
        ))}
      </div>

      <div className="export-canvas__footer">
        Generated by Reverse: 1999 Box Generator
      </div>
    </div>
  );
}
