import type { Character, CharacterState } from "../types/character";
import type { LangCode } from "../store/boxStore";
import { USER_ID_MAX } from "../store/boxStore";
import { getDisplayName } from "../utils/i18n";
import { getUiText } from "../i18n/ui";
import { prefixedAvatarPath } from "../utils/assets";
import { PortrayBadge } from "./PortrayBadge";

interface ExportCanvasProps {
  /** 過濾後的角色清單（未來視/持有模式/搜尋/星數） */
  characters: Character[];
  states: Record<string, CharacterState>;
  activeVariant: Record<string, string>;
  lang: LangCode;
  userId: string;
}

/** 離屏匯出層 */
export function ExportCanvas({
  characters,
  states,
  activeVariant,
  lang,
  userId,
}: ExportCanvasProps) {
  const t = getUiText(lang);
  const owned = characters.filter((c) => states[c.id]?.owned);
  const fullPortray = owned.filter(
    (c) => states[c.id]?.portray === 5
  ).length;
  const columns = owned.length > 60 ? 15 : owned.length > 30 ? 10 : Math.min(owned.length, 5) || 1;
  const gridWidth = columns * 114 + (columns - 1) * 10;

  return (
    <div className="export-canvas" style={{ width: gridWidth + 100 }}>
      {userId && (
        <div className="export-canvas__user-id">
          {userId.length > USER_ID_MAX ? userId.slice(0, USER_ID_MAX) + "..." : userId}
        </div>
      )}
      <div className="export-canvas__header">
        <div>
          <span className="export-canvas__eyebrow">{t.eyebrow}</span>
          <h2 className="export-canvas__title">{t.appTitle}</h2>
        </div>
        <div className="export-canvas__stats">
          <span>
            {t.owned} {owned.length} / {characters.length}
          </span>
          <span>
            {t.fullPortray} {fullPortray}
          </span>
        </div>
      </div>

      <div
        className="export-grid"
        style={{ gridTemplateColumns: `repeat(${columns}, auto)` }}
      >
        {owned.length === 0 ? (
          <div className="export-canvas__empty">
            <img
              src={import.meta.env.BASE_URL + "assets/vertin_question.png"}
              alt=""
              className="export-canvas__empty-image"
            />
            <p className="export-canvas__empty-text">{t.exportEmptyTitle}</p>
          </div>
        ) : (
          owned.map((character) => {
            const variantId =
              activeVariant[character.id] ?? character.defaultVariant;
            const src = prefixedAvatarPath(variantId);

            return (
              <div key={character.id} className="export-card">
                <div className="export-card__image-frame">
                  <img
                    className="export-card__image"
                    src={src}
                    alt={getDisplayName(character, lang)}
                  />
                  <PortrayBadge
                    level={states[character.id]?.portray ?? 0}
                    lang={lang}
                    position="bottom"
                  />
                </div>
                <div className="export-card__name">
                  {getDisplayName(character, lang)}
                </div>
              </div>
            );
          })
        )}
      </div>

      <div className="export-canvas__footer">
        Generated by GitHub.com/UnderLotus/r1999-roster
      </div>
    </div>
  );
}
