// URL 分享 token regressions: v1 compatibility, v2 exact identity, and sanitization.
import assert from "node:assert/strict";

import { characterCatalog } from "../src/data/characters";
import {
  decodeShareCode,
  encodeShareCode,
  sanitizeSharePayload,
} from "../src/utils/share-code";
import { createVariantIdentityCatalog } from "../src/domain/variant-identity";
import type { Character } from "../src/types/character";

function assertEqual<T>(actual: T, expected: T, message: string): void {
  assert.deepEqual(actual, expected, message);
  console.log(`ok: ${message}`);
}

function assertThrows(action: () => unknown, message: string): void {
  assert.throws(action);
  console.log(`ok: ${message}`);
}

function characterByBase(baseId: number): Character {
  const character = characterCatalog.getCharacterByBaseId(baseId);
  assert.ok(character, `catalog contains baseId ${baseId}`);
  return character;
}

function skinCharacter(variantId: string): Character {
  const character = characterCatalog.getCharacterByVariantId(variantId);
  assert.ok(character, `catalog owns ${variantId}`);
  return character;
}

const character3088 = characterByBase(3088);
const character3066 = characterByBase(3066);
const ordinarySkinCharacter = skinCharacter("314903");

// Fixed non-empty v2 golden token: custom skin encoding must remain stable,
// and the expected token is intentionally not generated by this test.
const goldenCharacter: Character = {
  id: "character-alpha",
  name: "Synthetic",
  baseId: 1234,
  releaseOrder: 1,
  enabled: true,
  stage: "live",
  isReleased: true,
  defaultVariant: "701001",
  skins: [
    { variantId: "701001", type: "default", skinName: null, skinNameEng: null },
    { variantId: "701002", type: "insight", skinName: null, skinNameEng: null },
    { variantId: "701777", type: "skin", skinName: null, skinNameEng: null },
  ],
};
const goldenIdentity = createVariantIdentityCatalog([goldenCharacter]);
const goldenPayload = {
  characters: { [goldenCharacter.id]: { owned: true, portray: 1 as const } },
  activeVariant: { [goldenCharacter.id]: "701777" },
  customVariants: { [goldenCharacter.id]: true as const },
  defaultSkinMode: "initial" as const,
  showFutureSight: false,
};
const goldenToken = "IgImkQETSAVaqIA";
assert.equal(encodeShareCode(goldenPayload, goldenIdentity), goldenToken);
const goldenDecoded = decodeShareCode(goldenToken, goldenIdentity);
assert.ok(goldenDecoded);
assertEqual(goldenDecoded?.activeVariant, goldenPayload.activeVariant, "fixed v2 golden custom skin decodes");


// Empty v2 token: version 2 preserves the historical header semantics.
{
  const token = encodeShareCode({
    characters: {},
    activeVariant: {},
    customVariants: {},
    defaultSkinMode: "initial",
    showFutureSight: false,
  });
  assert.equal(token, "IAA");
  assert.ok(decodeShareCode(token));
  assertEqual(decodeShareCode(token)?.characters, {}, "empty v2 token round-trips");
}

// v2 keeps both exact eight-digit IDs, an ordinary skin, portray levels, and flags.
{
  const payload = {
    characters: {
      [character3088.id]: { owned: true, portray: 0 as const },
      [character3066.id]: { owned: true, portray: 5 as const },
      [ordinarySkinCharacter.id]: { owned: true, portray: 2 as const },
    },
    activeVariant: {
      [character3088.id]: "30880001",
      [character3066.id]: "30660001",
      [ordinarySkinCharacter.id]: "314903",
    },
    customVariants: {
      [character3088.id]: true,
      [character3066.id]: true,
      [ordinarySkinCharacter.id]: true,
    } as Record<string, true>,
    defaultSkinMode: "insight" as const,
    showFutureSight: true,
  };
  const token = encodeShareCode(payload);
  const decoded = decodeShareCode(token);
  assert.ok(decoded, "v2 mixed payload decodes");
  assertEqual(decoded?.characters, payload.characters, "v2 portray and ownership round-trip");
  assertEqual(decoded?.activeVariant, payload.activeVariant, "v2 exact Variant IDs round-trip");
  assertEqual(decoded?.customVariants, payload.customVariants, "v2 customVariants round-trip");
  assert.equal(decoded?.defaultSkinMode, "insight");
  assert.equal(decoded?.showFutureSight, true);
}

// Fixed historical fixture: v1 [baseId=3088, portray=3, suffix=03].
// This fixture is independent of the v2 encoder and must remain decodable.
{
  const decoded = decodeShareCode("HgJggwEwQBg");
  assert.equal(decoded?.characters[character3088.id]?.portray, 3);
  assert.equal(decoded?.activeVariant[character3088.id], "308803");
  assert.equal(decoded?.customVariants[character3088.id], true);
  assert.equal(decoded?.defaultSkinMode, "insight");
  assert.equal(decoded?.showFutureSight, true);
  assertEqual(decodeShareCode("EAA")?.characters, {}, "historical empty v1 fixture decodes");
}

// A v1 suffix 01 must reconstruct only the historical six-digit default, not
// an eight-digit skin ending in 01. v2 is the lossless path for that skin.
{
  const v1Suffix01 = "HgJggwEwQAg"; // same fixture shape with suffix 01
  const decoded = decodeShareCode(v1Suffix01);
  assert.equal(decoded?.activeVariant[character3088.id], "308801");
  assert.notEqual(decoded?.activeVariant[character3088.id], "30880001");
  const v2 = encodeShareCode({
    characters: { [character3088.id]: { owned: true, portray: 0 } },
    activeVariant: { [character3088.id]: "30880001" },
    customVariants: { [character3088.id]: true },
    defaultSkinMode: "initial",
    showFutureSight: true,
  });
  assert.equal(decodeShareCode(v2)?.activeVariant[character3088.id], "30880001");
}

// Wrong-owner variants are discarded while valid owned Characters survive.
{
  const result = sanitizeSharePayload({
    charEntries: [
      [character3088.baseId, 0],
      [character3066.baseId, 5],
      [9999, 4],
      [character3088.baseId, 3],
    ],
    skinEntries: [
      [character3088.baseId, "30660001"],
      [character3088.baseId, "30880001"],
      [character3066.baseId, "30660001"],
    ],
    defaultSkinMode: "initial",
    showFutureSight: false,
  });
  assert.equal(result.characters[character3088.id]?.portray, 0);
  assert.equal(result.characters[character3066.id]?.portray, 5);
  assert.equal(result.activeVariant[character3088.id], "30880001");
  assert.equal(result.activeVariant[character3066.id], "30660001");
  assert.equal(Object.keys(result.characters).length, 2);
}

// The share adapter also works with an explicit catalog whose Character ID and
// default Variant cannot be reconstructed from its baseId.
{
  const synthetic: Character = {
    id: "character-alpha",
    name: "Synthetic",
    baseId: 1234,
    releaseOrder: 1,
    enabled: true,
    stage: "live",
    isReleased: true,
    defaultVariant: "701001",
    skins: [
      { variantId: "701001", type: "default", skinName: null, skinNameEng: null },
      { variantId: "701002", type: "insight", skinName: null, skinNameEng: null },
      { variantId: "701777", type: "skin", skinName: null, skinNameEng: null },
    ],
  };
  const identity = createVariantIdentityCatalog([synthetic]);
  assert.equal(identity.resolveModeVariant(synthetic.id, "initial"), "701001");
  assert.equal(identity.resolveModeVariant(synthetic.id, "insight"), "701002");
  const token = encodeShareCode(
    {
      characters: { [synthetic.id]: { owned: true, portray: 1 } },
      activeVariant: { [synthetic.id]: "701777" },
      customVariants: { [synthetic.id]: true },
      defaultSkinMode: "initial",
      showFutureSight: false,
    },
    identity
  );
  const decoded = decodeShareCode(token, identity);
  assert.equal(decoded?.characters[synthetic.id]?.portray, 1);
  assert.equal(decoded?.activeVariant[synthetic.id], "701777");
}

// Unsupported valid numeric identities fail explicitly rather than truncating.
{
  const unsupported: Character = {
    id: "character-large-variant",
    name: "Unsupported",
    baseId: 1235,
    releaseOrder: 1,
    enabled: true,
    stage: "live",
    isReleased: true,
    defaultVariant: "702001",
    skins: [
      { variantId: "702001", type: "default", skinName: null, skinNameEng: null },
      { variantId: "134217728", type: "skin", skinName: null, skinNameEng: null },
    ],
  };
  const identity = createVariantIdentityCatalog([unsupported]);
  assertThrows(
    () =>
      encodeShareCode(
        {
          characters: { [unsupported.id]: { owned: true, portray: 0 } },
          activeVariant: { [unsupported.id]: "134217728" },
          customVariants: { [unsupported.id]: true },
          defaultSkinMode: "initial",
          showFutureSight: false,
        },
        identity
      ),
    "v2 rejects Variant IDs outside 27-bit range"
  );
}

// Malformed, truncated, unknown-version, and trailing-data tokens reject.
assert.equal(decodeShareCode(""), null);
assert.equal(decodeShareCode("!!!not-base64url!!!"), null);
{
  const token = encodeShareCode({
    characters: { [character3088.id]: { owned: true, portray: 0 } },
    activeVariant: {},
    customVariants: {},
    defaultSkinMode: "initial",
    showFutureSight: false,
  });
  assert.equal(decodeShareCode(token.slice(0, -1)), null);
  assert.equal(decodeShareCode(`${token}A`), null);
}
{
  const versionZero = "AAA";
  assert.equal(decodeShareCode(versionZero), null);
}
console.log("ok: malformed/version/trailing-data handling");

console.log("Share-code regressions passed.");
